services:
  lumen:
    build: ./lumen-app
    ports:
      - '8000:8000'
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: energex
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
    volumes:
      - ./lumen-app:/var/www

  node-cache-api:
    build: ./node-cache-api
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: energex
    volumes:
      - ./node-cache-api:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: energex
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - '6379:6379'

volumes:
  mysql-data:
